var express = require('express')
var path = require('path')
var serveStatic = require('serve-static')
app = express()
app.use(serveStatic(__dirname + '/dist'))
app.use(serveStatic(__dirname + '/src'))
var port = process.env.PORT || 5001;
app.listen(port)
console.log('server started '+ port)
console.log(__dirname + '/src/chess/js/chess/chessboard-1.0.0.js')